[project]
name = "labml"
version = "0.1.0"
description = ""
authors = [
    {name = "Puiu Ioan Alexandru",email = "ionutpuiu010405@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel (>=7.4.0,<8.0.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "pandas (>=3.0.6,<4.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "scikit-learn (>=1.9.1,<2.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pylint (>=4.1.2,<5.0.0)"
]
